project:
  type: website
  output-dir: docs

website:
  title: "Lucian Blue Scher"
  # favicon: images/favicon.png
  navbar:
    logo: /images/
    #logo-alt: The name lucian scher with a logo image
    title: false
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: "Lucian's Log"
      # - href: resources.qmd
      #   text: Resources
      - icon: github
        href: https://github.com/lucianbluescher
  page-footer:
    left: Copyright 2025, Lucian Scher

      

format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full
    mainfont: Oswald



